type: app
description: Default stackfile usecase create REST APIs with ability Logging, Documentation, RDBMS and Clients HTTP
# template used to create the project
template: java-springboot-restapi-stack/default-template
# list of plugins to be applied after project creation
plugins:
  - plugin: java-springboot-restapi-stack/java-spring-data-jpa-plugin
  - plugin: java-springboot-restapi-stack/java-spring-security-oauth2-resourceserver-plugin   
  - plugin: java-springboot-restapi-stack/java-spring-open-feign-plugin   
